#!/bin/zsh

# Set dotfiles/.zshrc as current .zshrc file
cp ~/.zshrc.pre-oh-my-zsh ~/.zshrc

# Install Powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
